apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankingTeam
  labels:
    app: bankingTeam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bankingTeam
  template:
    metadata:
      labels:
        app: bankingTeam
    spec:
      containers:
        - name: bankingTeam
          image: username/bankingTeam:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5