apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerTeam
  labels:
    app: customerTeam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerTeam
  template:
    metadata:
      labels:
        app: customerTeam
    spec:
      containers:
        - name: CustomerTeam
          image: username/customerTeam:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5