---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: Login
  labels:
    app: Login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Login
  template:
    metadata:
      labels:
        app: Login
    spec:
      containers:
        - name: Login
          image: username/Login:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: CustomerTeam
  labels:
    app: CustomerTeam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: CustomerTeam
  template:
    metadata:
      labels:
        app: CustomerTeam
    spec:
      containers:
        - name: CustomerTeam
          image: username/CustomerTeam:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankingTeam
  labels:
    app: BankingTeam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankingTeam
  template:
    metadata:
      labels:
        app: BankingTeam
    spec:
      containers:
        - name: BankingTeam
          image: username/BankingTeam:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: DepositTeam
  labels:
    app: DepositTeam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DepositTeam
  template:
    metadata:
      labels:
        app: DepositTeam
    spec:
      containers:
        - name: DepositTeam
          image: username/DepositTeam:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: Login
  labels:
    app: Login
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: Login


---


apiVersion: v1
kind: Service
metadata:
  name: CustomerTeam
  labels:
    app: CustomerTeam
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: CustomerTeam


---


apiVersion: v1
kind: Service
metadata:
  name: BankingTeam
  labels:
    app: BankingTeam
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BankingTeam


---


apiVersion: v1
kind: Service
metadata:
  name: DepositTeam
  labels:
    app: DepositTeam
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: DepositTeam

