apiVersion: apps/v1
kind: Deployment
metadata:
  name: customerinfo
  labels:
    app: customerinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customerinfo
  template:
    metadata:
      labels:
        app: customerinfo
    spec:
      containers:
        - name: customerinfo
          image: username/customerinfo:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5