apiVersion: apps/v1
kind: Deployment
metadata:
  name: DepositTeam
  labels:
    app: DepositTeam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: DepositTeam
  template:
    metadata:
      labels:
        app: DepositTeam
    spec:
      containers:
        - name: DepositTeam
          image: username/DepositTeam:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5